export const GET_USERS_REQUESTED = "GET_USERS_REQUESTED";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SAGA = "DELETE_USER_SAGA";
export const UPDATE_USER = "UPDATE_USER";
